test: cards.o deck.o future.o input.o test-future.c
	gcc -g -std=gnu99 -Wall -Werror cards.o deck.o future.o input.o test-input.c
cards.o: cards.c 
	gcc -g -std=gnu99 -Wall -Werror -c cards.c
deck.o:  deck.c
	gcc -g -std=gnu99 -Wall -Werror -c  deck.c
future.o:  future.c
	gcc -g -std=gnu99 -Wall -Werror -c future.c
input.o:  input.c
	gcc -g -std=gnu99 -Wall -Werror -c input.c
